name: Docker Compose CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate-docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Load environment variables
        uses: appleboy/load-env-action@v2
        with:
          envFile: .env.database

      - name: Validate compose.yaml
        run: docker compose config

      - name: Build Docker images
        run: docker compose build --pull

      - name: Start containers
        run: docker compose up -d

      - name: Wait for PostgreSQL
        run: docker compose wait database

      - name: Check PostgreSQL connectivity
        run: docker compose exec database pg_isready -U ${POSTGRES_USER}

      - name: Check pgAdmin health
        run: |
          curl -s -o /dev/null -w "%{http_code}" http://localhost:15432/login | grep 200

      - name: Stop containers
        run: docker compose down -v
        if: always()